name: reVC premake x86

on:
  pull_request:
  push:
  release:
    types: [published]

env:
  GLFW_VER: "3.3.2"
  GLFW_BASE: "glfw-3.3.2.bin.WIN32"
  GLFW_FILE: "glfw-3.3.2.bin.WIN32.zip"
  GLFW_URL: "https://github.com/glfw/glfw/releases/download/3.3.2/glfw-3.3.2.bin.WIN32.zip"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [win-x86-librw_d3d9-mss, win-x86-librw_gl3_glfw-mss, win-x86-librw_d3d9-oal, win-x86-librw_gl3_glfw-oal]
        buildtype: [Debug, Release, Vanilla]
        include:
          - platform: win-x86-librw_gl3_glfw-mss
            glfw_required: true

    steps:
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4
        with:
          submodules: 'true'

      - name: Download GLFW (if needed)
        if: matrix.glfw_required
        uses: actions/download-artifact@v3
        with:
          name: glfw-bin

      - name: Download GLFW (if needed)
        if
