name: reVC premake amd64

on:
  pull_request:
  push:
  release:
    types: [published]

env:
  GLFW_VER: "3.3.2"
  GLFW_BASE: "glfw-3.3.2.bin.WIN64"
  GLFW_FILE: "glfw-3.3.2.bin.WIN64.zip"
  GLFW_URL: "https://github.com/glfw/glfw/releases/download/3.3.2/glfw-3.3.2.bin.WIN64.zip"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [win-amd64-librw_d3d9-oal, win-amd64-librw_gl3_glfw-oal]
        buildtype: [Debug, Release]
        include:
          - platform: win-amd64-librw_gl3_glfw-oal
            glfw_required: true

    steps:
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Download GLFW (if needed)
        if: matrix.glfw_required
        uses: actions/download-artifact@v3 # For downloading cached GLFW
        with:
          name: glfw-bin-amd64

      - name: Download GLFW (if needed)
        if: matrix.glfw_required && steps.download-artifact.outcome == 'failure'
        run: |
          Invoke-WebRequest -Uri ${{ env.GLFW_URL }} -OutFile ${{ env.GLFW_FILE }}
          7z x ${{ env.GLFW_FILE }}

      - name: Configure build
        run: |
        ./premake5 vs2019 --with-librw --no-full-paths --glfwdir64=${{ env.GLFW_BASE }}

      - name: Build
        run: |
          msbuild -m build/reVC.sln /property:Configuration=${{ matrix.buildtype }} /property:Platform=${{ matrix.platform }}

      - name: Move binaries to gamefiles
        run: |
          mkdir -p gamefiles
          Copy-Item -Path "./bin/${{ matrix.platform }}/${{ matrix.buildtype }}/reVC.exe" -Destination "./gamefiles/"
          Copy-Item -Path "./bin/${{ matrix.platform }}/${{ matrix.buildtype }}/reVC.pdb" -Destination "./gamefiles/"

      - name: Move dynamic dependencies to gamefiles
        run: |
          Copy-Item -Path "./vendor/mpg123/dist/Win64/libmpg123-0.dll" -Destination "./gamefiles/"
          Copy-Item -Path "./vendor/openal-soft/dist/Win64/OpenAL32.dll" -Destination "./gamefiles/"

      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Correct version!
        with:
          name: reVC_${{ matrix.buildtype }}_${{ matrix.platform }}
          path:./gamefiles/*

  build_glfw_amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: glfw/glfw
          path: glfw-src

      - name: Build GLFW
        run: |
          cd glfw-src
          mkdir build
          cd build
          cmake.. -A x64
          msbuild GLFW.sln /property:Configuration=Release

      - name: Upload GLFW binary artifact
        uses: actions/upload-artifact@v4 # Correct version!
        with:
          name: glfw-bin-amd64
          path: glfw-src/build/src/Release/glfw3.dll
